"use client";

import type React from "react";

import { useState, useRef, useEffect } from "react";
import { DashboardLayout } from "@/components/dashboard-layout";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Send, Settings, Copy, CheckCircle2, AlertCircle } from "lucide-react";

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
  codeBlock?: {
    language: string;
    code: string;
  };
}

export default function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      role: "assistant",
      content:
        "Hello! I'm InfraPilot AI, your infrastructure automation assistant. I can help you generate, review, and execute infrastructure scripts. What would you like to automate today?",
      timestamp: new Date(),
    },
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;

    // Add user message
    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: input,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setLoading(true);

    // Simulate AI response
    setTimeout(() => {
      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content:
          "I'll generate an infrastructure script for you based on your request.",
        timestamp: new Date(),
        codeBlock: {
          language: "bash",
          code: `#!/bin/bash
# Infrastructure automation script
set -e

echo "Starting infrastructure deployment..."

# Your automation code here
# This is a placeholder generated by AI

echo "Deployment completed successfully!"`,
        },
      };
      setMessages((prev) => [...prev, assistantMessage]);
      setLoading(false);
    }, 1500);
  };

  const handleCopyCode = (id: string, code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <DashboardLayout>
      <div className="space-y-6 mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold">AI Script Generator</h1>
            <p className="text-muted-foreground mt-1">
              Generate infrastructure scripts using natural language
            </p>
          </div>
          <Button variant="outline" size="icon">
            <Settings className="w-5 h-5" />
          </Button>
        </div>

        {/* Chat Container */}
        <Card className="flex flex-col h-[600px]">
          {/* Messages Area */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {messages.map((message) => (
              <div
                key={message.id}
                className={`flex ${
                  message.role === "user" ? "justify-end" : "justify-start"
                }`}
              >
                <div
                  className={`max-w-2xl ${
                    message.role === "user"
                      ? "bg-primary text-primary-foreground rounded-lg rounded-tr-none"
                      : "bg-muted text-foreground rounded-lg rounded-tl-none"
                  } p-4`}
                >
                  <p className="text-sm leading-relaxed mb-2">
                    {message.content}
                  </p>

                  {message.codeBlock && (
                    <div className="mt-4 bg-background/50 rounded-lg overflow-hidden">
                      <div className="flex items-center justify-between bg-muted px-4 py-2 border-b border-border">
                        <span className="text-xs font-mono text-muted-foreground">
                          {message.codeBlock.language}
                        </span>
                        <Button
                          size="sm"
                          variant="ghost"
                          className="h-6 w-6 p-0"
                          onClick={() =>
                            handleCopyCode(message.id, message.codeBlock!.code)
                          }
                        >
                          {copiedId === message.id ? (
                            <CheckCircle2 className="w-4 h-4 text-green-500" />
                          ) : (
                            <Copy className="w-4 h-4" />
                          )}
                        </Button>
                      </div>
                      <pre className="p-4 overflow-x-auto">
                        <code className="text-xs font-mono text-foreground">
                          {message.codeBlock.code}
                        </code>
                      </pre>
                    </div>
                  )}

                  {message.role === "assistant" && message.codeBlock && (
                    <div className="mt-4 flex gap-2">
                      <Button size="sm" className="gap-2">
                        <CheckCircle2 className="w-4 h-4" />
                        Execute
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        className="gap-2 bg-transparent"
                      >
                        <AlertCircle className="w-4 h-4" />
                        Dry Run
                      </Button>
                    </div>
                  )}

                  <p className="text-xs opacity-70 mt-2">
                    {message.timestamp.toLocaleTimeString([], {
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                  </p>
                </div>
              </div>
            ))}

            {loading && (
              <div className="flex justify-start">
                <div className="bg-muted text-foreground rounded-lg rounded-tl-none p-4">
                  <div className="flex gap-2 items-center">
                    <div className="w-2 h-2 rounded-full bg-muted-foreground animate-bounce" />
                    <div
                      className="w-2 h-2 rounded-full bg-muted-foreground animate-bounce"
                      style={{ animationDelay: "0.1s" }}
                    />
                    <div
                      className="w-2 h-2 rounded-full bg-muted-foreground animate-bounce"
                      style={{ animationDelay: "0.2s" }}
                    />
                  </div>
                </div>
              </div>
            )}

            <div ref={messagesEndRef} />
          </div>

          {/* Input Area */}
          <div className="border-t border-border p-6 bg-card">
            <form onSubmit={handleSendMessage} className="flex gap-3">
              <Input
                placeholder="Describe the infrastructure task you need to automate..."
                value={input}
                onChange={(e) => setInput(e.target.value)}
                disabled={loading}
                className="flex-1"
              />
              <Button
                type="submit"
                disabled={loading || !input.trim()}
                className="gap-2"
              >
                <Send className="w-4 h-4" />
                <span className="hidden sm:inline">Send</span>
              </Button>
            </form>

            {/* Help Text */}
            <div className="mt-4 grid grid-cols-2 sm:grid-cols-3 gap-2">
              {[
                "Deploy Kubernetes",
                "Setup CI/CD",
                "Database Backup",
                "SSL Certificate",
                "VPC Setup",
                "Auto Scaling",
              ].map((example) => (
                <button
                  key={example}
                  onClick={() => setInput(example)}
                  className="text-xs p-2 rounded-md border border-border hover:bg-muted transition-colors text-muted-foreground hover:text-foreground text-left"
                >
                  {example}
                </button>
              ))}
            </div>
          </div>
        </Card>

        {/* Features */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Card className="p-4">
            <h3 className="font-semibold text-sm mb-2">Natural Language</h3>
            <p className="text-xs text-muted-foreground">
              Describe tasks in plain English and AI generates code
            </p>
          </Card>
          <Card className="p-4">
            <h3 className="font-semibold text-sm mb-2">Dry Run Mode</h3>
            <p className="text-xs text-muted-foreground">
              Preview changes before executing in production
            </p>
          </Card>
          <Card className="p-4">
            <h3 className="font-semibold text-sm mb-2">Instant Execute</h3>
            <p className="text-xs text-muted-foreground">
              Run scripts directly to your infrastructure
            </p>
          </Card>
        </div>
      </div>
    </DashboardLayout>
  );
}
